### ISSUE TITLE
Documentation Help needed

### ISSUE THREAD

**Issue by sivsivsree** [sivsivsree/file-service#12]
Need help for setting up documentations

**Comment by gleeny** [comment]
I can help you with this later today probably.

**Comment by gleeny** [comment]
I'm sorry, I haven't made things with docker-compose etc. I can't make documentation, not with the current knowledge I have. But I wish to try it out soon. I'm unassigning myself, so someone else can do it.

**Comment by sivsivsree** [comment]
> I'm sorry, I haven't made things with docker-compose etc. I can't make documentation, not with the current knowledge I have. But I wish to try it out soon. I'm unassigning myself, so someone else can do it.

You are welcome.
